#!/usr/bin/python

import SocketServer
import optparse
import sys

LOCAL_ADDRESS = "localhost"
LOCAL_PORT = 13337

from common import CNFFormula

from solvers import PortfolioSolver
from solvers import ExternalSolver

from optparse import OptionParser

_solverPaths = []

def parseBinaryFormula(inputFile):
    pass

def emitBinarySolution(outputFile, solution):
    pass

def createPortfolioSolver():
    solvers = []
    
    for path in _solverPaths:
        solvers.append(ExternalSolver(path))
        
    portfolio = PortfolioSolver(solvers)
    
    return portfolio

class ServerHandler(SocketServer.StreamRequestHandler):
    def handle(self):
        formula = parseBinaryFormula(self.rfile)
        solver = createPortfolioSolver()
        
        solution = solver.solve(formula)
        
        emitBinarySolution(self.wfile, solution)
        

def main():
    parser = OptionParser()
    parser.add_option("-s", "--solver", action="append", dest="solver_paths")
    
    (options, args) = parser.parse_args()
    
    if options.solver_paths is None:
        sys.stderr.write("You need to specify at least one solver.\n")
        exit(1)
        
    global _solverPaths
    _solverPaths = options.solver_paths
    
    server = SocketServer.TCPServer((LOCAL_ADDRESS, LOCAL_PORT), ServerHandler)
    
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print "Server stopped."

if __name__ == "__main__":
    main()